### ISSUE TITLE
Searcharr Recently Stopped Working

### ISSUE THREAD

**Issue by abracadabra1111** [toddrob99/searcharr#56]
I've been running searcharr for around 10 months or so and it's been great. Recently realized that the telegram bot stopped responding to inquiries. Searcharr container log shows the following recurring error. Any ideas what's causing the problem?
```
Traceback (most recent call last):

  File "/app/searcharr.py", line 1775, in <module>

    tgr.run()

  File "/app/searcharr.py", line 1435, in run

    updater.start_polling()

  File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 422, in start_polling

    self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)

  File "/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py", line 342, in _init_thread

    name=f"Bot:{self.bot.id}:{name}",

  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 369, in id

    return self.bot.id

  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 363, in bot

    self._bot = self.get_me()

  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator

    result = func(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 450, in get_me

    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)

  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post

    return self.request.post(

  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post

    result = self._request_wrapper(

  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 265, in _request_wrapper

    raise NetworkError(f'urllib3 HTTPError {error}') from error

telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botXXXXXX:XXXXXXXXX/getMe (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7ea5b64640>: Failed to establish a new connection: [Errno -3] Try again'))
```

**Comment by toddrob99** [comment]
Have you tried restarting the container? It is a connection issue between your container and the Telegram API.

**Comment by abracadabra1111** [comment]
> Have you tried restarting the container? It is a connection issue between your container and the Telegram API.

I did, but same error. It's currently tunneled through a VPN, so I'll try running it as a standalone.

**Comment by abracadabra1111** [comment]
> > Have you tried restarting the container? It is a connection issue between your container and the Telegram API.
> 
> I did, but same error. It's currently tunneled through a VPN, so I'll try running it as a standalone.

Makes no difference whether I'm running it through VPN container or as a bridge network in docker. Same error persists. I have about 30 other docker containers and no other connectivity problems elsewhere. Not sure if there's some other problem related to api.telegram.org.

**Comment by toddrob99** [comment]
Have you tried running it in `host` network mode? Or running from source to rule out docker? It's working fine for many people, so I don't think there's a searcharr problem here.

**Comment by abracadabra1111** [comment]
> Have you tried running it in `host` network mode? Or running from source to rule out docker? It's working fine for many people, so I don't think there's a searcharr problem here.

Looks like some network issue I need to sort out. Container working fine in a separate User bridge network.

**Comment by toddrob99** [comment]
Good luck!
